apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: creatio
  namespace: creatio
spec:
  rules:
    - host: creatio.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: creatio
                port:
                  number: 5000
